### ISSUE TITLE
Linux compilation support

### ISSUE THREAD

**Issue by micwoj92** [Tkain/TF2CLauncher#1]
Linux support

**Comment by Tkain** [comment]
This launcher primarily exists because Steam's built-in handling of Source Engine mods on Windows has two main bugs: it doesn't initialize the Steam overlay for Source mods correctly and it doesn't pass through arguments supplied to the game through the Steam client.

As far as I know, these bugs aren't present on Steam's Linux client, so Linux users should find Steam's built-in entry for Team Fortress 2 Classic adequate for launching the game (provided they add `-steam -steam` to the game's launch entry arguments).

**Comment by micwoj92** [comment]
Sorry, I should be more specific rather than only writing "linux support"
It would be great to be able to at least to crosscompile it on linux, it's not possible currently, because it relies on visual studio which is windows only. But I can see why this would be out of scope too.

**Comment by Tkain** [comment]
Oh, I see what you mean. I've been meaning to figure out how to set per-platform build targets recently, so I'll look into seeing if I can make the GNU toolset an option.
